import type { PlutusScript } from '@meshsdk/core';

// Compiled Aiken validator — generated by running:
//   cd contracts/litecert-registry
//   aiken build
//   cat plutus.json | jq '.validators[0].compiledCode'
//
// Then set NEXT_PUBLIC_CONTRACT_COMPILED_CODE in .env.local
const COMPILED_CODE = process.env.NEXT_PUBLIC_CONTRACT_COMPILED_CODE ?? '';

if (!COMPILED_CODE && typeof window !== 'undefined') {
  console.warn(
    '[LiteCert] Contract compiled code not set. ' +
    'Run `aiken build` inside contracts/litecert-registry then set ' +
    'NEXT_PUBLIC_CONTRACT_COMPILED_CODE in .env.local'
  );
}

export const certificateRegistryScript: PlutusScript = {
  code: COMPILED_CODE,
  version: 'V3',
};

export function isContractDeployed(): boolean {
  return COMPILED_CODE.length > 0;
}
